export const  levels = [
  {
    level: 0,
    name: "Initiate",
    min: 0,
    max: 0,
    des: "Starting point (no role).",
  },
  {
    level: 1,
    name: "Disciple",
    min: 1,
    max: 499,
    des: "Entry-level role for early contributions.",
  },
  {
    level: 2,
    name: "Seeker",
    min: 500,
    max: 2000,
    des: "Growing activity and consisitent participation.",
  },
  {
    level: 3,
    name: "Adept",
    min: 2001,
    max: 5000,
    des: "Steady progress with quality content and invites.",
  },
  {
    level: 4,
    name: "Vanguard",
    min: 5001,
    max: 10000,
    des: "Significant contributions, visuals, and events.",
  },
  {
    level: 5,
    name: "Luminary",
    min: 10001,
    max: 20000,
    des: "Recognized as a leader, quality content creator.",
  },
  {
    level: 6,
    name: "Archon",
    min: 20001,
    max: 35000,
    des: "Advanced role for community influencers.",
  },
  {
    level: 7,
    name: "Paragon",
    min: 35001,
    max: 50000,
    des: "Top-tier leadership and event organizers.",
  },
  {
    level: 8,
    name: "Sovereign",
    min: 50001,
    max: 75000,
    des: "Elite role for high-level contributions.",
  },
  {
    level: 9,
    name: "EDITH Overlord",
    min: 75001,
    max: 0,
    des: "The ultimate title for legendary contributiors.",
  },
]